# Generated by Django 2.0.1 on 2018-01-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('solved_timestamp', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
    ]
