# Generated by Django 2.0.1 on 2018-01-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='solved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
